/**
 * Demo-only tool catalog for the Governed Research Runtime. Every tool here
 * returns deterministic, locally-defined demonstration data — there are no
 * real web calls, no API keys, no live integrations, and no external system
 * writes. `demo_crm_update` exists specifically to prove the runtime refuses
 * unsafe tools: it is a WRITE_ACTION with externalAccess=true,
 * approvalMode=FORBIDDEN, and enabled=false.
 */

import type { ToolDefinition } from "./types";

export const demoTools: ToolDefinition[] = [
  {
    id: "demo_web_search",
    name: "Demo Web Search",
    nameAr: "بحث ويب تجريبي",
    description: "Simulated web search returning fixed demonstration snippets — no real network access.",
    descriptionAr: "بحث ويب محاكى يعيد مقتطفات تجريبية ثابتة — بدون أي وصول فعلي للشبكة.",
    toolType: "WEB_SEARCH",
    system: "Demo Search Index",
    actionType: "READ",
    readWriteClass: "READ_ONLY",
    dataClasses: ["low", "medium"],
    externalAccess: false,
    requiredAuthority: false,
    approvalMode: "NONE",
    reversible: true,
    auditRequired: true,
    maxCallsPerRun: 4,
    enabled: true,
    demoOnly: true,
  },
  {
    id: "demo_document_search",
    name: "Demo Document Search",
    nameAr: "بحث مستندات تجريبي",
    description: "Simulated internal document retrieval over a fixed local demonstration corpus.",
    descriptionAr: "استرجاع مستندات داخلية محاكى فوق مجموعة مستندات تجريبية محلية ثابتة.",
    toolType: "DOCUMENT_RETRIEVAL",
    system: "Demo Document Repository",
    actionType: "READ",
    readWriteClass: "READ_ONLY",
    dataClasses: ["low", "medium", "high"],
    externalAccess: false,
    requiredAuthority: false,
    approvalMode: "NONE",
    reversible: true,
    auditRequired: true,
    maxCallsPerRun: 4,
    enabled: true,
    demoOnly: true,
  },
  {
    id: "demo_internal_policy_lookup",
    name: "Demo Internal Policy Lookup",
    nameAr: "الاطلاع على السياسات الداخلية (تجريبي)",
    description: "Simulated lookup against a fixed local snapshot of internal governance policy summaries.",
    descriptionAr: "اطلاع محاكى على لقطة محلية ثابتة لملخصات سياسات الحوكمة الداخلية.",
    toolType: "INTERNAL_DATA_LOOKUP",
    system: "Demo Policy Repository",
    actionType: "READ",
    readWriteClass: "READ_ONLY",
    dataClasses: ["low", "medium"],
    externalAccess: false,
    requiredAuthority: false,
    approvalMode: "NONE",
    reversible: true,
    auditRequired: true,
    maxCallsPerRun: 3,
    enabled: true,
    demoOnly: true,
  },
  {
    id: "demo_calculator",
    name: "Demo Calculator",
    nameAr: "آلة حاسبة تجريبية",
    description: "Deterministic local arithmetic helper for scoring and aggregation steps.",
    descriptionAr: "أداة حسابية محلية حتمية لخطوات الترقيم والتجميع.",
    toolType: "CALCULATOR",
    system: "Local",
    actionType: "ANALYSIS",
    readWriteClass: "READ_ONLY",
    dataClasses: ["low"],
    externalAccess: false,
    requiredAuthority: false,
    approvalMode: "NONE",
    reversible: true,
    auditRequired: false,
    maxCallsPerRun: 6,
    enabled: true,
    demoOnly: true,
  },
  {
    id: "demo_report_builder",
    name: "Demo Report Builder",
    nameAr: "منشئ تقارير تجريبي",
    description: "Assembles collected evidence and findings into a structured draft report — generation only, no external write.",
    descriptionAr: "يجمّع الأدلة والنتائج في تقرير مسودة منظم — توليد فقط، بدون أي كتابة خارجية.",
    toolType: "REPORT_GENERATOR",
    system: "Local",
    actionType: "GENERATION",
    readWriteClass: "READ_ONLY",
    dataClasses: ["low", "medium", "high"],
    externalAccess: false,
    requiredAuthority: false,
    approvalMode: "PRE_APPROVAL",
    reversible: true,
    auditRequired: true,
    maxCallsPerRun: 2,
    enabled: true,
    demoOnly: true,
  },
  {
    id: "demo_crm_update",
    name: "Demo CRM Update (Prohibited)",
    nameAr: "تحديث نظام العملاء (ممنوع)",
    description: "Demonstration of a forbidden tool — a live external write action that this runtime must always refuse to execute.",
    descriptionAr: "توضيح لأداة ممنوعة — إجراء كتابة خارجي حي يجب على هذا النظام رفض تنفيذه دائمًا.",
    toolType: "WRITE_ACTION",
    system: "CRM Platform",
    actionType: "WRITE",
    readWriteClass: "WRITE",
    dataClasses: ["medium", "high"],
    externalAccess: true,
    requiredAuthority: true,
    approvalMode: "FORBIDDEN",
    reversible: false,
    auditRequired: true,
    maxCallsPerRun: 0,
    enabled: false,
    demoOnly: true,
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return demoTools.find((t) => t.id === id);
}
