/**
 * NEXGEGL-owned internal skill catalog for the Governed Research Runtime.
 * All instruction content below is original to this product — no
 * third-party SKILL.md text is copied. Each skill is a bounded, reviewed
 * procedure, not a general-purpose capability. `approvedForUse` defaults to
 * true only for these five reviewed internal skills; any newly-intaken
 * skill (see skill-loader.ts / /skills/intake) starts at false.
 */

import type { SkillDefinition } from "./types";

export const demoSkills: SkillDefinition[] = [
  {
    id: "institutional-research-planning",
    name: "Institutional Research Planning",
    nameAr: "تخطيط البحث المؤسسي",
    version: "1.0.0",
    description: "Turns an institutional research request into a bounded, auditable research objective and step outline.",
    descriptionAr: "يحوّل طلب بحث مؤسسي إلى هدف بحثي محدود وقابل للتدقيق مع مخطط خطوات.",
    sourceType: "INTERNAL",
    sourceReference: "internal://nexgegl/skills/institutional-research-planning@1.0.0",
    category: "planning",
    triggerConditions: ["طلب بحث مؤسسي جديد", "الحاجة لتحليل مخاطر اعتماد ذكاء اصطناعي أو وكيل"],
    requiredTools: [],
    allowedDataClasses: ["low", "medium", "high"],
    prohibitedDataClasses: [],
    requiredAuthority: false,
    actionType: "ANALYSIS",
    reversibility: "REVERSIBLE",
    externalSystemAccess: false,
    writeCapability: false,
    auditRequired: true,
    humanApprovalRequired: false,
    riskLevel: "low",
    reviewStatus: "APPROVED_FOR_DEMO",
    approvedForUse: true,
    checksum: "sha256-demo-irp-1a2b3c",
    lastReviewed: "2026-07-10",
    reviewer: "AI Governance Office",
    instructions: [
      "حدد نطاق السؤال البحثي وصنّفه ضمن فئة الحوكمة المناسبة.",
      "لا تصدر أي توصية أو قرار في هذه المرحلة — الناتج خطة بحث فقط.",
      "ارفض أي طلب مباشر لإصدار قرار رسمي أو موافقة إنتاج أو حكم KFSA.",
      "حدد الأدلة المطلوبة والصلاحية المؤسسية اللازمة قبل المتابعة.",
    ],
    riskProfile: { writeCapability: false, externalSystemAccess: false, dataSensitivityHandled: "medium", requiresHumanApproval: false },
  },
  {
    id: "evidence-collection",
    name: "Evidence Collection",
    nameAr: "جمع الأدلة",
    version: "1.0.0",
    description: "Collects evidence items from approved read-only tools within the bounds of the governed plan.",
    descriptionAr: "يجمع عناصر الأدلة من الأدوات المعتمدة للقراءة فقط ضمن حدود الخطة المحكومة.",
    sourceType: "INTERNAL",
    sourceReference: "internal://nexgegl/skills/evidence-collection@1.0.0",
    category: "research",
    triggerConditions: ["وجود خطوة بحث تتطلب أدلة موثقة"],
    requiredTools: ["demo_web_search", "demo_document_search", "demo_internal_policy_lookup"],
    allowedDataClasses: ["low", "medium", "high"],
    prohibitedDataClasses: [],
    requiredAuthority: false,
    actionType: "READ",
    reversibility: "REVERSIBLE",
    externalSystemAccess: false,
    writeCapability: false,
    auditRequired: true,
    humanApprovalRequired: false,
    riskLevel: "low",
    reviewStatus: "APPROVED_FOR_DEMO",
    approvedForUse: true,
    checksum: "sha256-demo-ec-4d5e6f",
    lastReviewed: "2026-07-10",
    reviewer: "AI Governance Office",
    instructions: [
      "استخدم فقط الأدوات المعتمدة ضمن الخطة.",
      "سجّل مصدر كل دليل وتاريخ التقاطه ودرجة جودته.",
      "لا يُعتبر أي دليل مقبولًا تلقائيًا — يبقى بحالة غير مراجَع حتى تُراجعه جهة بشرية.",
    ],
    riskProfile: { writeCapability: false, externalSystemAccess: false, dataSensitivityHandled: "medium", requiresHumanApproval: false },
  },
  {
    id: "source-quality-review",
    name: "Source Quality Review",
    nameAr: "مراجعة جودة المصادر",
    version: "1.0.0",
    description: "Assesses the quality, freshness, and provenance of collected evidence before evaluation.",
    descriptionAr: "يقيّم جودة الأدلة المجمعة وحداثتها ومصدرها قبل مرحلة التقييم.",
    sourceType: "INTERNAL",
    sourceReference: "internal://nexgegl/skills/source-quality-review@1.0.0",
    category: "quality",
    triggerConditions: ["اكتمال جمع الأدلة لخطوة بحثية"],
    requiredTools: ["demo_calculator"],
    allowedDataClasses: ["low", "medium", "high"],
    prohibitedDataClasses: [],
    requiredAuthority: false,
    actionType: "ANALYSIS",
    reversibility: "REVERSIBLE",
    externalSystemAccess: false,
    writeCapability: false,
    auditRequired: true,
    humanApprovalRequired: false,
    riskLevel: "low",
    reviewStatus: "APPROVED_FOR_DEMO",
    approvedForUse: true,
    checksum: "sha256-demo-sqr-7g8h9i",
    lastReviewed: "2026-07-10",
    reviewer: "AI Governance Office",
    instructions: [
      "قيّم كل دليل على أساس الجودة والحداثة ووضوح المصدر.",
      "ارفع أي دليل ناقص الجودة كنقطة ضعف صريحة في التقييم بدل تجاهله.",
      "لا تُحسّن تصنيف الجودة لتفادي نتيجة إصلاح أو تصعيد.",
    ],
    riskProfile: { writeCapability: false, externalSystemAccess: false, dataSensitivityHandled: "medium", requiresHumanApproval: false },
  },
  {
    id: "governance-risk-analysis",
    name: "Governance Risk Analysis",
    nameAr: "تحليل مخاطر الحوكمة",
    version: "1.0.0",
    description: "Analyzes collected evidence against governance policy to surface risks, gaps, and required controls.",
    descriptionAr: "يحلل الأدلة المجمعة مقابل سياسة الحوكمة لإبراز المخاطر والفجوات والضوابط المطلوبة.",
    sourceType: "INTERNAL",
    sourceReference: "internal://nexgegl/skills/governance-risk-analysis@1.0.0",
    category: "governance",
    triggerConditions: ["اكتمال مراجعة جودة المصادر"],
    requiredTools: ["demo_internal_policy_lookup", "demo_calculator"],
    allowedDataClasses: ["low", "medium", "high"],
    prohibitedDataClasses: [],
    requiredAuthority: true,
    actionType: "ANALYSIS",
    reversibility: "REVERSIBLE",
    externalSystemAccess: false,
    writeCapability: false,
    auditRequired: true,
    humanApprovalRequired: true,
    riskLevel: "medium",
    reviewStatus: "APPROVED_FOR_DEMO",
    approvedForUse: true,
    checksum: "sha256-demo-gra-1j2k3l",
    lastReviewed: "2026-07-10",
    reviewer: "AI Governance Office",
    instructions: [
      "قارن نتائج الأدلة بسياسة الحوكمة الداخلية وحدد الضوابط الناقصة.",
      "صنّف الخطورة والحاجة لتصعيد أو إصلاح دون إصدار قرار مؤسسي.",
      "لا تفترض وجود صلاحية مؤسسية غير موثقة في الطلب.",
    ],
    riskProfile: { writeCapability: false, externalSystemAccess: false, dataSensitivityHandled: "high", requiresHumanApproval: true },
  },
  {
    id: "decision-packet-drafting",
    name: "Decision Packet Drafting",
    nameAr: "صياغة حزمة القرار",
    version: "1.0.0",
    description: "Assembles a draft, preliminary decision packet from the run's evidence, evaluations, and findings.",
    descriptionAr: "يجمّع حزمة قرار تمهيدية من أدلة التشغيل وتقييماته ونتائجه.",
    sourceType: "INTERNAL",
    sourceReference: "internal://nexgegl/skills/decision-packet-drafting@1.0.0",
    category: "reporting",
    triggerConditions: ["اكتمال تحليل مخاطر الحوكمة"],
    requiredTools: ["demo_report_builder"],
    allowedDataClasses: ["low", "medium", "high"],
    prohibitedDataClasses: [],
    requiredAuthority: false,
    actionType: "GENERATION",
    reversibility: "REVERSIBLE",
    externalSystemAccess: false,
    writeCapability: false,
    auditRequired: true,
    humanApprovalRequired: true,
    riskLevel: "medium",
    reviewStatus: "APPROVED_FOR_DEMO",
    approvedForUse: true,
    checksum: "sha256-demo-dpd-4m5n6o",
    lastReviewed: "2026-07-10",
    reviewer: "AI Governance Office",
    instructions: [
      "لخّص الأدلة والتقييمات والنتائج بإيجاز تنفيذي.",
      "ضع دائمًا جملة الحدود التنظيمية في نهاية الحزمة.",
      "لا تُصدر توصية نهائية أو قرارًا رسميًا أو حكم KFSA — الحزمة تمهيدية فقط.",
    ],
    riskProfile: { writeCapability: false, externalSystemAccess: false, dataSensitivityHandled: "medium", requiresHumanApproval: true },
  },
];

export function getSkillById(id: string): SkillDefinition | undefined {
  return demoSkills.find((s) => s.id === id);
}
