/**
 * Realistic mock data for the Agent Governance Control Plane MVP.
 * Frontend-only, no backend, no database. All values are illustrative.
 */

import type { UseCase } from "./governance-model";

export const useCases: UseCase[] = [
  {
    id: "uc-01",
    name: "Internal Policy Search Assistant",
    nameAr: "مساعد البحث في السياسات الداخلية",
    department: "Operations",
    owner: "Fahad Al-Otaibi — Operations Manager",
    authority: "Operations Director",
    aiType: "Retrieval Assistant (Chat)",
    businessPurpose:
      "Answers employee questions from internal HR and operations policy documents without requiring direct contact with HR or Legal.",
    riskLevel: "low",
    dataSensitivity: "low",
    toolAccess: "none",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["Internal policy repository"],
    governanceStatus: "READY_FOR_AUTHORITY_REVIEW",
    evalScore: 96,
    evalOutcome: "PASS",
    readinessScore: 91,
    evidenceStatus: "complete",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "blocked",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-06-28",
    auditTrailStatus: "present",
    connectedSystems: ["Policy Repository"],
    timeline: [
      { date: "2026-06-10", event: "تم تصنيف حالة الاستخدام كأتمتة (AUTOMATION)", actor: "Governance Intake" },
      { date: "2026-06-20", event: "اجتاز مصفوفة التقييم (96/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-06-28", event: "تم تحديدها كجاهزة لمراجعة صاحب الصلاحية", actor: "Governance Gate" },
    ],
  },
  {
    id: "uc-02",
    name: "Customer Email Response Copilot",
    nameAr: "مساعد الرد على بريد العملاء",
    department: "Customer Service",
    owner: "Lama Al-Harbi — CS Team Lead",
    authority: "Customer Service Director",
    aiType: "Drafting Copilot (Assisted)",
    businessPurpose: "Drafts suggested replies to customer emails for a human agent to review and send.",
    riskLevel: "medium",
    dataSensitivity: "medium",
    toolAccess: "write",
    externalSystems: [],
    writeTools: ["Email draft composer"],
    readOnlyTools: ["Customer support tickets"],
    governanceStatus: "REPAIR_REQUIRED",
    evalScore: 71,
    evalOutcome: "FIX",
    readinessScore: 74,
    evidenceStatus: "partial",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: false,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "allowed",
      read_crm: "allowed",
      update_crm: "forbidden",
      send_email: "requires_approval",
      export_data: "forbidden",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-02",
    auditTrailStatus: "present",
    connectedSystems: ["Helpdesk Platform"],
    timeline: [
      { date: "2026-06-12", event: "تم تصنيف حالة الاستخدام كتعزيز (AUGMENTATION)", actor: "Governance Intake" },
      { date: "2026-06-24", event: "رصد التقييم نقصًا في دليل الإسناد المرجعي", actor: "Eval & Grader Matrix" },
      { date: "2026-07-02", event: "تم التوجيه إلى الإصلاح لاستكمال دليل التقييم", actor: "Governance Gate" },
    ],
  },
  {
    id: "uc-03",
    name: "CRM Update Agent",
    nameAr: "وكيل تحديث نظام العملاء",
    department: "Sales",
    owner: "Yousef Al-Qahtani — Sales Ops Manager",
    authority: "Sales Director",
    aiType: "Write Agent",
    businessPurpose: "Automatically updates CRM records after sales calls based on call transcripts.",
    riskLevel: "medium",
    dataSensitivity: "medium",
    toolAccess: "write",
    externalSystems: [],
    writeTools: ["CRM record updater"],
    readOnlyTools: ["Call transcripts"],
    governanceStatus: "GOVERNANCE_REVIEW_REQUIRED",
    evalScore: 82,
    evalOutcome: "PASS",
    readinessScore: 79,
    evidenceStatus: "partial",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: false,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "allowed",
      read_crm: "allowed",
      update_crm: "requires_approval",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "allowed",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-06-30",
    auditTrailStatus: "present",
    connectedSystems: ["CRM Platform"],
    timeline: [
      { date: "2026-06-05", event: "تم تصنيف حالة الاستخدام كوكيل (AGENT)", actor: "Governance Intake" },
      { date: "2026-06-22", event: "اجتاز مصفوفة التقييم (82/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-06-30", event: "تم ترشيحها لمراجعة الحوكمة — حدود السياسة غير مكتملة", actor: "Governance Gate" },
    ],
  },
  {
    id: "uc-04",
    name: "Finance Variance Explanation Assistant",
    nameAr: "مساعد تفسير الانحرافات المالية",
    department: "Finance",
    owner: "Noura Al-Dossary — FP&A Manager",
    authority: "CFO Office",
    aiType: "Analysis Assistant (Read-only)",
    businessPurpose: "Explains monthly budget variance drivers to finance leadership using ERP financial data.",
    riskLevel: "medium",
    dataSensitivity: "high",
    toolAccess: "read_only",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["ERP financial reports"],
    governanceStatus: "READY_FOR_AUTHORITY_REVIEW",
    evalScore: 93,
    evalOutcome: "PASS",
    readinessScore: 88,
    evidenceStatus: "complete",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "requires_approval",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-05",
    auditTrailStatus: "present",
    connectedSystems: ["ERP System"],
    timeline: [
      { date: "2026-06-08", event: "تم تصنيف حالة الاستخدام كتعزيز (AUGMENTATION)", actor: "Governance Intake" },
      { date: "2026-06-27", event: "اجتاز مصفوفة التقييم (93/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-07-05", event: "تم تحديدها كجاهزة لمراجعة صاحب الصلاحية", actor: "Governance Gate" },
    ],
  },
  {
    id: "uc-05",
    name: "Procurement Vendor Screening Assistant",
    nameAr: "مساعد فحص الموردين",
    department: "Operations",
    owner: "Khalid Al-Zahrani — Procurement Manager",
    authority: "Chief Procurement Officer",
    aiType: "Decision-Support Assistant",
    businessPurpose: "Screens new vendor applications against compliance and risk criteria before onboarding.",
    riskLevel: "high",
    dataSensitivity: "medium",
    toolAccess: "external_system",
    externalSystems: ["Third-party vendor verification service"],
    writeTools: [],
    readOnlyTools: ["Procurement records"],
    governanceStatus: "ESCALATE_REQUIRED",
    evalScore: 68,
    evalOutcome: "ESCALATE",
    readinessScore: 61,
    evidenceStatus: "partial",
    authorityStatus: "escalation_required",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: false,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: false,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "requires_approval",
      external_api_access: "requires_approval",
    },
    lastReviewed: "2026-06-20",
    auditTrailStatus: "partial",
    connectedSystems: ["Vendor Verification API"],
    timeline: [
      { date: "2026-05-30", event: "تم تصنيف حالة الاستخدام كتشغيل محكوم (GOVERNED_RUNTIME)", actor: "Governance Intake" },
      { date: "2026-06-14", event: "رصد التقييم غموضًا في صلاحية اتخاذ القرار", actor: "Eval & Grader Matrix" },
      { date: "2026-06-20", event: "تم التصعيد — لا توجد صلاحية معتمدة لرفض المورد", actor: "Governance Gate" },
    ],
  },
  {
    id: "uc-06",
    name: "HR CV Screening Assistant",
    nameAr: "مساعد فرز السير الذاتية",
    department: "HR",
    owner: "Sara Al-Ghamdi — Talent Acquisition Lead",
    authority: "CHRO Office",
    aiType: "Decision-Support Assistant",
    businessPurpose: "Screens and ranks incoming CVs against job requirements before recruiter review.",
    riskLevel: "high",
    dataSensitivity: "high",
    toolAccess: "read_only",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["Applicant tracking system"],
    governanceStatus: "BLOCKED",
    evalScore: 42,
    evalOutcome: "FAIL",
    readinessScore: 38,
    evidenceStatus: "missing",
    authorityStatus: "missing",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: false,
      eval_evidence: false,
      audit_evidence: false,
      policy_boundary_evidence: false,
      approval_evidence: false,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-06-15",
    auditTrailStatus: "missing",
    connectedSystems: ["Applicant Tracking System"],
    timeline: [
      { date: "2026-06-01", event: "تم تصنيف حالة الاستخدام كتشغيل محكوم (GOVERNED_RUNTIME)", actor: "Governance Intake" },
      { date: "2026-06-15", event: "فشل التقييم — لا توجد صلاحية معتمدة ولا سجل تدقيق", actor: "Eval & Grader Matrix" },
      { date: "2026-06-15", event: "تم الحظر لحين استكمال دليل المالك والصلاحية", actor: "Governance Gate" },
    ],
  },
  {
    id: "uc-07",
    name: "Board Report Summarization Assistant",
    nameAr: "مساعد تلخيص تقارير مجلس الإدارة",
    department: "Executive Office",
    owner: "Abdullah Al-Rashid — Chief of Staff",
    authority: "CEO Office",
    aiType: "Summarization Assistant",
    businessPurpose: "Summarizes department reports into a concise briefing ahead of board meetings.",
    riskLevel: "low",
    dataSensitivity: "medium",
    toolAccess: "read_only",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["Department report repository"],
    governanceStatus: "READY_FOR_AUTHORITY_REVIEW",
    evalScore: 90,
    evalOutcome: "PASS",
    readinessScore: 85,
    evidenceStatus: "complete",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "requires_approval",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-08",
    auditTrailStatus: "present",
    connectedSystems: ["Board Portal"],
    timeline: [
      { date: "2026-06-18", event: "تم تصنيف حالة الاستخدام كتعزيز (AUGMENTATION)", actor: "Governance Intake" },
      { date: "2026-06-29", event: "اجتاز مصفوفة التقييم (90/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-07-08", event: "تم تحديدها كجاهزة لمراجعة صاحب الصلاحية", actor: "Governance Gate" },
    ],
  },
  {
    id: "uc-08",
    name: "Collection Prioritization Agent",
    nameAr: "وكيل ترتيب أولويات التحصيل",
    department: "Finance",
    owner: "Mansour Al-Shehri — Collections Manager",
    authority: "CFO Office",
    aiType: "Decision-Support Agent",
    businessPurpose: "Prioritizes overdue customer accounts for collections outreach based on default risk.",
    riskLevel: "high",
    dataSensitivity: "high",
    toolAccess: "external_system",
    externalSystems: ["Collections agency system"],
    writeTools: ["Outreach queue prioritizer"],
    readOnlyTools: ["Accounts receivable data"],
    governanceStatus: "ESCALATE_REQUIRED",
    evalScore: 64,
    evalOutcome: "ESCALATE",
    readinessScore: 58,
    evidenceStatus: "partial",
    authorityStatus: "escalation_required",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: false,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: false,
      approval_evidence: false,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "allowed",
      read_crm: "allowed",
      update_crm: "requires_approval",
      send_email: "forbidden",
      export_data: "requires_approval",
      trigger_workflow: "requires_approval",
      external_api_access: "requires_approval",
    },
    lastReviewed: "2026-06-18",
    auditTrailStatus: "partial",
    connectedSystems: ["Collections Agency System"],
    timeline: [
      { date: "2026-05-25", event: "تم تصنيف حالة الاستخدام كتشغيل محكوم (GOVERNED_RUNTIME)", actor: "Governance Intake" },
      { date: "2026-06-10", event: "رصد التقييم تصعيدًا بسبب التأثير على العملاء", actor: "Eval & Grader Matrix" },
      { date: "2026-06-18", event: "تم التصعيد — لا توجد صلاحية معتمدة لترتيب أولويات التواصل", actor: "Governance Gate" },
    ],
  },
  {
    id: "uc-09",
    name: "Sales Forecasting Assistant",
    nameAr: "مساعد التنبؤ بالمبيعات",
    department: "Sales",
    owner: "Reem Al-Subaie — Sales Analytics Manager",
    authority: "Sales Director",
    aiType: "Forecasting Assistant (Read-only)",
    businessPurpose: "Generates quarterly sales forecasts from historical pipeline data for planning.",
    riskLevel: "low",
    dataSensitivity: "low",
    toolAccess: "read_only",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["Sales pipeline data"],
    governanceStatus: "READY_FOR_AUTHORITY_REVIEW",
    evalScore: 89,
    evalOutcome: "PASS",
    readinessScore: 84,
    evidenceStatus: "complete",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "forbidden",
      read_crm: "allowed",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "requires_approval",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-01",
    auditTrailStatus: "present",
    connectedSystems: ["Sales Pipeline Dashboard"],
    timeline: [
      { date: "2026-06-11", event: "تم تصنيف حالة الاستخدام كتعزيز (AUGMENTATION)", actor: "Governance Intake" },
      { date: "2026-06-23", event: "اجتاز مصفوفة التقييم (89/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-07-01", event: "تم تحديدها كجاهزة لمراجعة صاحب الصلاحية", actor: "Governance Gate" },
    ],
  },
  {
    id: "uc-10",
    name: "Contract Clause Risk Reviewer",
    nameAr: "مراجع مخاطر بنود العقود",
    department: "Legal",
    owner: "Hana Al-Amri — Legal Counsel",
    authority: "General Counsel",
    aiType: "Review Assistant (Decision-relevant)",
    businessPurpose: "Flags high-risk clauses in vendor and customer contracts before legal sign-off.",
    riskLevel: "medium",
    dataSensitivity: "medium",
    toolAccess: "read_only",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["Contract repository"],
    governanceStatus: "GOVERNANCE_REVIEW_REQUIRED",
    evalScore: 78,
    evalOutcome: "PASS",
    readinessScore: 72,
    evidenceStatus: "partial",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: false,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "requires_approval",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-06-25",
    auditTrailStatus: "present",
    connectedSystems: ["Contract Repository"],
    timeline: [
      { date: "2026-06-02", event: "تم تصنيف حالة الاستخدام كتعزيز (AUGMENTATION)", actor: "Governance Intake" },
      { date: "2026-06-19", event: "اجتاز مصفوفة التقييم (78/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-06-25", event: "تم ترشيحها لمراجعة الحوكمة — تأثير نظامي/قانوني متوسط", actor: "Governance Gate" },
    ],
  },
  {
    id: "uc-11",
    name: "Customer Churn Prediction Workflow",
    nameAr: "سير عمل التنبؤ بتسرب العملاء",
    department: "Customer Service",
    owner: "Faisal Al-Mutairi — CX Insights Lead",
    authority: "Customer Service Director",
    aiType: "Prediction Workflow",
    businessPurpose: "Predicts which customers are at risk of churn to prioritize retention outreach.",
    riskLevel: "medium",
    dataSensitivity: "medium",
    toolAccess: "write",
    externalSystems: [],
    writeTools: ["Retention queue updater"],
    readOnlyTools: ["Customer usage data"],
    governanceStatus: "REPAIR_REQUIRED",
    evalScore: 73,
    evalOutcome: "FIX",
    readinessScore: 70,
    evidenceStatus: "partial",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: false,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "allowed",
      read_crm: "allowed",
      update_crm: "requires_approval",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "requires_approval",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-03",
    auditTrailStatus: "present",
    connectedSystems: ["Customer Analytics Platform"],
    timeline: [
      { date: "2026-06-14", event: "تم تصنيف حالة الاستخدام كسير عمل (WORKFLOW)", actor: "Governance Intake" },
      { date: "2026-06-27", event: "رصد التقييم نقصًا في دليل تقييم نموذج تسرب العملاء", actor: "Eval & Grader Matrix" },
      { date: "2026-07-03", event: "تم التوجيه إلى الإصلاح لاستكمال دليل التقييم", actor: "Governance Gate" },
    ],
  },
  {
    id: "uc-12",
    name: "External API Workflow Agent",
    nameAr: "وكيل سير عمل واجهات خارجية",
    department: "Operations",
    owner: "Turki Al-Anazi — Automation Engineer",
    authority: "COO Office",
    aiType: "Autonomous Workflow Agent",
    businessPurpose: "Autonomously orchestrates multi-step operational workflows across internal and external systems.",
    riskLevel: "high",
    dataSensitivity: "medium",
    toolAccess: "external_system",
    externalSystems: ["Third-party logistics API", "Partner billing API"],
    writeTools: ["Workflow orchestrator"],
    readOnlyTools: [],
    governanceStatus: "BLOCKED",
    evalScore: 35,
    evalOutcome: "FAIL",
    readinessScore: 30,
    evidenceStatus: "missing",
    authorityStatus: "missing",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: false,
      eval_evidence: false,
      audit_evidence: false,
      policy_boundary_evidence: false,
      approval_evidence: false,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "blocked",
      external_api_access: "blocked",
    },
    lastReviewed: "2026-06-10",
    auditTrailStatus: "missing",
    connectedSystems: ["Logistics API", "Billing API"],
    timeline: [
      { date: "2026-05-20", event: "تم تصنيف حالة الاستخدام كنظام متعدد الوكلاء (MULTI_AGENT_SYSTEM)", actor: "Governance Intake" },
      { date: "2026-06-10", event: "فشل التقييم — لا توجد حدود سياسة ولا سجل تدقيق", actor: "Eval & Grader Matrix" },
      { date: "2026-06-10", event: "تم الحظر لحين استكمال دليل الصلاحية وحدود السياسة", actor: "Governance Gate" },
    ],
  },
];

export function getUseCaseById(id: string): UseCase | undefined {
  return useCases.find((u) => u.id === id);
}
