/**
 * Realistic mock data for the NEXGEGL AI Governance Operating System MVP.
 * Frontend-only, no backend, no database. All values are illustrative and
 * cover all eight governance layers: AI Inventory & Ownership, Data
 * Foundation, Model Lifecycle, Data Security & Privacy, Access Control,
 * Agent Governance, Human Oversight, and Compliance & Audit.
 */

import type { UseCase } from "./governance-model";
import type {
  Agent,
  AuditEvent,
  ComplianceMapping,
  DataLineageRecord,
  DataSource,
  EvaluationRecord,
  HumanReview,
  IncidentRecord,
  ModelRecord,
  PrivacyControl,
  SecurityControl,
  VendorRecord,
} from "./types";

export const useCases: UseCase[] = [
  {
    id: "uc-01",
    name: "Internal Policy Search Assistant",
    nameAr: "مساعد البحث في السياسات الداخلية",
    department: "Operations",
    owner: "Fahad Al-Otaibi — Operations Manager",
    authority: "Operations Director",
    aiType: "Retrieval Assistant (Chat)",
    businessPurpose:
      "Answers employee questions from internal HR and operations policy documents without requiring direct contact with HR or Legal.",
    riskLevel: "low",
    dataSensitivity: "low",
    toolAccess: "none",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["Internal policy repository"],
    governanceStatus: "READY_FOR_AUTHORITY_REVIEW",
    evalScore: 96,
    evalOutcome: "PASS",
    readinessScore: 91,
    evidenceStatus: "complete",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "blocked",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-06-28",
    auditTrailStatus: "present",
    connectedSystems: ["Policy Repository"],
    timeline: [
      { date: "2026-06-10", event: "تم تصنيف حالة الاستخدام كأتمتة (AUTOMATION)", actor: "Governance Intake" },
      { date: "2026-06-20", event: "اجتاز مصفوفة التقييم (96/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-06-28", event: "تم تحديدها كجاهزة لمراجعة صاحب الصلاحية", actor: "Governance Gate" },
    ],
    lifecycleStage: "governed_runtime",
    agentIds: [],
    modelId: "model-005",
    dataSourceIds: ["ds-001"],
  },
  {
    id: "uc-02",
    name: "Customer Email Response Copilot",
    nameAr: "مساعد الرد على بريد العملاء",
    department: "Customer Service",
    owner: "Lama Al-Harbi — CS Team Lead",
    authority: "Customer Service Director",
    aiType: "Drafting Copilot (Assisted)",
    businessPurpose: "Drafts suggested replies to customer emails for a human agent to review and send.",
    riskLevel: "medium",
    dataSensitivity: "medium",
    toolAccess: "write",
    externalSystems: [],
    writeTools: ["Email draft composer"],
    readOnlyTools: ["Customer support tickets"],
    governanceStatus: "REPAIR_REQUIRED",
    evalScore: 71,
    evalOutcome: "FIX",
    readinessScore: 74,
    evidenceStatus: "partial",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: false,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "allowed",
      read_crm: "allowed",
      update_crm: "forbidden",
      send_email: "requires_approval",
      export_data: "forbidden",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-02",
    auditTrailStatus: "present",
    connectedSystems: ["Helpdesk Platform"],
    timeline: [
      { date: "2026-06-12", event: "تم تصنيف حالة الاستخدام كتعزيز (AUGMENTATION)", actor: "Governance Intake" },
      { date: "2026-06-24", event: "رصد التقييم نقصًا في دليل الإسناد المرجعي", actor: "Eval & Grader Matrix" },
      { date: "2026-07-02", event: "تم التوجيه إلى الإصلاح لاستكمال دليل التقييم", actor: "Governance Gate" },
    ],
    lifecycleStage: "pilot",
    agentIds: ["agent-001"],
    modelId: "model-001",
    dataSourceIds: ["ds-002"],
  },
  {
    id: "uc-03",
    name: "CRM Update Agent",
    nameAr: "وكيل تحديث نظام العملاء",
    department: "Sales",
    owner: "Yousef Al-Qahtani — Sales Ops Manager",
    authority: "Sales Director",
    aiType: "Write Agent",
    businessPurpose: "Automatically updates CRM records after sales calls based on call transcripts.",
    riskLevel: "medium",
    dataSensitivity: "medium",
    toolAccess: "write",
    externalSystems: [],
    writeTools: ["CRM record updater"],
    readOnlyTools: ["Call transcripts"],
    governanceStatus: "GOVERNANCE_REVIEW_REQUIRED",
    evalScore: 82,
    evalOutcome: "PASS",
    readinessScore: 79,
    evidenceStatus: "partial",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: false,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "allowed",
      read_crm: "allowed",
      update_crm: "requires_approval",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "allowed",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-06-30",
    auditTrailStatus: "present",
    connectedSystems: ["CRM Platform"],
    timeline: [
      { date: "2026-06-05", event: "تم تصنيف حالة الاستخدام كوكيل (AGENT)", actor: "Governance Intake" },
      { date: "2026-06-22", event: "اجتاز مصفوفة التقييم (82/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-06-30", event: "تم ترشيحها لمراجعة الحوكمة — حدود السياسة غير مكتملة", actor: "Governance Gate" },
    ],
    lifecycleStage: "governed_runtime",
    agentIds: ["agent-002"],
    modelId: "model-002",
    dataSourceIds: ["ds-003"],
  },
  {
    id: "uc-04",
    name: "Finance Variance Explanation Assistant",
    nameAr: "مساعد تفسير الانحرافات المالية",
    department: "Finance",
    owner: "Noura Al-Dossary — FP&A Manager",
    authority: "CFO Office",
    aiType: "Analysis Assistant (Read-only)",
    businessPurpose: "Explains monthly budget variance drivers to finance leadership using ERP financial data.",
    riskLevel: "medium",
    dataSensitivity: "high",
    toolAccess: "read_only",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["ERP financial reports"],
    governanceStatus: "READY_FOR_AUTHORITY_REVIEW",
    evalScore: 93,
    evalOutcome: "PASS",
    readinessScore: 88,
    evidenceStatus: "complete",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "requires_approval",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-05",
    auditTrailStatus: "present",
    connectedSystems: ["ERP System"],
    timeline: [
      { date: "2026-06-08", event: "تم تصنيف حالة الاستخدام كتعزيز (AUGMENTATION)", actor: "Governance Intake" },
      { date: "2026-06-27", event: "اجتاز مصفوفة التقييم (93/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-07-05", event: "تم تحديدها كجاهزة لمراجعة صاحب الصلاحية", actor: "Governance Gate" },
    ],
    lifecycleStage: "governed_runtime",
    agentIds: [],
    modelId: "model-003",
    dataSourceIds: ["ds-004"],
  },
  {
    id: "uc-05",
    name: "Procurement Vendor Screening Assistant",
    nameAr: "مساعد فحص الموردين",
    department: "Operations",
    owner: "Khalid Al-Zahrani — Procurement Manager",
    authority: "Chief Procurement Officer",
    aiType: "Decision-Support Assistant",
    businessPurpose: "Screens new vendor applications against compliance and risk criteria before onboarding.",
    riskLevel: "high",
    dataSensitivity: "medium",
    toolAccess: "external_system",
    externalSystems: ["Third-party vendor verification service"],
    writeTools: [],
    readOnlyTools: ["Procurement records"],
    governanceStatus: "ESCALATE_REQUIRED",
    evalScore: 68,
    evalOutcome: "ESCALATE",
    readinessScore: 61,
    evidenceStatus: "partial",
    authorityStatus: "escalation_required",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: false,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: false,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "requires_approval",
      external_api_access: "requires_approval",
    },
    lastReviewed: "2026-06-20",
    auditTrailStatus: "partial",
    connectedSystems: ["Vendor Verification API"],
    timeline: [
      { date: "2026-05-30", event: "تم تصنيف حالة الاستخدام كتشغيل محكوم (GOVERNED_RUNTIME)", actor: "Governance Intake" },
      { date: "2026-06-14", event: "رصد التقييم غموضًا في صلاحية اتخاذ القرار", actor: "Eval & Grader Matrix" },
      { date: "2026-06-20", event: "تم التصعيد — لا توجد صلاحية معتمدة لرفض المورد", actor: "Governance Gate" },
    ],
    lifecycleStage: "governed_runtime",
    agentIds: ["agent-003"],
    modelId: "model-004",
    vendorId: "vendor-002",
    dataSourceIds: ["ds-005"],
  },
  {
    id: "uc-06",
    name: "HR CV Screening Assistant",
    nameAr: "مساعد فرز السير الذاتية",
    department: "HR",
    owner: "Sara Al-Ghamdi — Talent Acquisition Lead",
    authority: "CHRO Office",
    aiType: "Decision-Support Assistant",
    businessPurpose: "Screens and ranks incoming CVs against job requirements before recruiter review.",
    riskLevel: "high",
    dataSensitivity: "high",
    toolAccess: "read_only",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["Applicant tracking system"],
    governanceStatus: "BLOCKED",
    evalScore: 42,
    evalOutcome: "FAIL",
    readinessScore: 38,
    evidenceStatus: "missing",
    authorityStatus: "missing",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: false,
      eval_evidence: false,
      audit_evidence: false,
      policy_boundary_evidence: false,
      approval_evidence: false,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-06-15",
    auditTrailStatus: "missing",
    connectedSystems: ["Applicant Tracking System"],
    timeline: [
      { date: "2026-06-01", event: "تم تصنيف حالة الاستخدام كتشغيل محكوم (GOVERNED_RUNTIME)", actor: "Governance Intake" },
      { date: "2026-06-15", event: "فشل التقييم — لا توجد صلاحية معتمدة ولا سجل تدقيق", actor: "Eval & Grader Matrix" },
      { date: "2026-06-15", event: "تم الحظر لحين استكمال دليل المالك والصلاحية", actor: "Governance Gate" },
    ],
    lifecycleStage: "pilot",
    agentIds: [],
    modelId: "model-005",
    dataSourceIds: ["ds-006"],
  },
  {
    id: "uc-07",
    name: "Board Report Summarization Assistant",
    nameAr: "مساعد تلخيص تقارير مجلس الإدارة",
    department: "Executive Office",
    owner: "Abdullah Al-Rashid — Chief of Staff",
    authority: "CEO Office",
    aiType: "Summarization Assistant",
    businessPurpose: "Summarizes department reports into a concise briefing ahead of board meetings.",
    riskLevel: "low",
    dataSensitivity: "medium",
    toolAccess: "read_only",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["Department report repository"],
    governanceStatus: "READY_FOR_AUTHORITY_REVIEW",
    evalScore: 90,
    evalOutcome: "PASS",
    readinessScore: 85,
    evidenceStatus: "complete",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "requires_approval",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-08",
    auditTrailStatus: "present",
    connectedSystems: ["Board Portal"],
    timeline: [
      { date: "2026-06-18", event: "تم تصنيف حالة الاستخدام كتعزيز (AUGMENTATION)", actor: "Governance Intake" },
      { date: "2026-06-29", event: "اجتاز مصفوفة التقييم (90/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-07-08", event: "تم تحديدها كجاهزة لمراجعة صاحب الصلاحية", actor: "Governance Gate" },
    ],
    lifecycleStage: "governed_runtime",
    agentIds: [],
    modelId: "model-001",
    dataSourceIds: ["ds-007"],
  },
  {
    id: "uc-08",
    name: "Collection Prioritization Agent",
    nameAr: "وكيل ترتيب أولويات التحصيل",
    department: "Finance",
    owner: "Mansour Al-Shehri — Collections Manager",
    authority: "CFO Office",
    aiType: "Decision-Support Agent",
    businessPurpose: "Prioritizes overdue customer accounts for collections outreach based on default risk.",
    riskLevel: "high",
    dataSensitivity: "high",
    toolAccess: "external_system",
    externalSystems: ["Collections agency system"],
    writeTools: ["Outreach queue prioritizer"],
    readOnlyTools: ["Accounts receivable data"],
    governanceStatus: "ESCALATE_REQUIRED",
    evalScore: 64,
    evalOutcome: "ESCALATE",
    readinessScore: 58,
    evidenceStatus: "partial",
    authorityStatus: "escalation_required",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: false,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: false,
      approval_evidence: false,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "allowed",
      read_crm: "allowed",
      update_crm: "requires_approval",
      send_email: "forbidden",
      export_data: "requires_approval",
      trigger_workflow: "requires_approval",
      external_api_access: "requires_approval",
    },
    lastReviewed: "2026-06-18",
    auditTrailStatus: "partial",
    connectedSystems: ["Collections Agency System"],
    timeline: [
      { date: "2026-05-25", event: "تم تصنيف حالة الاستخدام كتشغيل محكوم (GOVERNED_RUNTIME)", actor: "Governance Intake" },
      { date: "2026-06-10", event: "رصد التقييم تصعيدًا بسبب التأثير على العملاء", actor: "Eval & Grader Matrix" },
      { date: "2026-06-18", event: "تم التصعيد — لا توجد صلاحية معتمدة لترتيب أولويات التواصل", actor: "Governance Gate" },
    ],
    lifecycleStage: "governed_runtime",
    agentIds: ["agent-004"],
    modelId: "model-002",
    vendorId: "vendor-003",
    dataSourceIds: ["ds-008"],
  },
  {
    id: "uc-09",
    name: "Sales Forecasting Assistant",
    nameAr: "مساعد التنبؤ بالمبيعات",
    department: "Sales",
    owner: "Reem Al-Subaie — Sales Analytics Manager",
    authority: "Sales Director",
    aiType: "Forecasting Assistant (Read-only)",
    businessPurpose: "Generates quarterly sales forecasts from historical pipeline data for planning.",
    riskLevel: "low",
    dataSensitivity: "low",
    toolAccess: "read_only",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["Sales pipeline data"],
    governanceStatus: "READY_FOR_AUTHORITY_REVIEW",
    evalScore: 89,
    evalOutcome: "PASS",
    readinessScore: 84,
    evidenceStatus: "complete",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "forbidden",
      read_crm: "allowed",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "requires_approval",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-01",
    auditTrailStatus: "present",
    connectedSystems: ["Sales Pipeline Dashboard"],
    timeline: [
      { date: "2026-06-11", event: "تم تصنيف حالة الاستخدام كتعزيز (AUGMENTATION)", actor: "Governance Intake" },
      { date: "2026-06-23", event: "اجتاز مصفوفة التقييم (89/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-07-01", event: "تم تحديدها كجاهزة لمراجعة صاحب الصلاحية", actor: "Governance Gate" },
    ],
    lifecycleStage: "governed_runtime",
    agentIds: [],
    modelId: "model-003",
    dataSourceIds: ["ds-009"],
  },
  {
    id: "uc-10",
    name: "Contract Clause Risk Reviewer",
    nameAr: "مراجع مخاطر بنود العقود",
    department: "Legal",
    owner: "Hana Al-Amri — Legal Counsel",
    authority: "General Counsel",
    aiType: "Review Assistant (Decision-relevant)",
    businessPurpose: "Flags high-risk clauses in vendor and customer contracts before legal sign-off.",
    riskLevel: "medium",
    dataSensitivity: "medium",
    toolAccess: "read_only",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["Contract repository"],
    governanceStatus: "GOVERNANCE_REVIEW_REQUIRED",
    evalScore: 78,
    evalOutcome: "PASS",
    readinessScore: 72,
    evidenceStatus: "partial",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: false,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "requires_approval",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-06-25",
    auditTrailStatus: "present",
    connectedSystems: ["Contract Repository"],
    timeline: [
      { date: "2026-06-02", event: "تم تصنيف حالة الاستخدام كتعزيز (AUGMENTATION)", actor: "Governance Intake" },
      { date: "2026-06-19", event: "اجتاز مصفوفة التقييم (78/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-06-25", event: "تم ترشيحها لمراجعة الحوكمة — تأثير نظامي/قانوني متوسط", actor: "Governance Gate" },
    ],
    lifecycleStage: "pilot",
    agentIds: [],
    modelId: "model-004",
    dataSourceIds: ["ds-010"],
  },
  {
    id: "uc-11",
    name: "Customer Churn Prediction Workflow",
    nameAr: "سير عمل التنبؤ بتسرب العملاء",
    department: "Customer Service",
    owner: "Faisal Al-Mutairi — CX Insights Lead",
    authority: "Customer Service Director",
    aiType: "Prediction Workflow",
    businessPurpose: "Predicts which customers are at risk of churn to prioritize retention outreach.",
    riskLevel: "medium",
    dataSensitivity: "medium",
    toolAccess: "write",
    externalSystems: [],
    writeTools: ["Retention queue updater"],
    readOnlyTools: ["Customer usage data"],
    governanceStatus: "REPAIR_REQUIRED",
    evalScore: 73,
    evalOutcome: "FIX",
    readinessScore: 70,
    evidenceStatus: "partial",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: false,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "allowed",
      read_crm: "allowed",
      update_crm: "requires_approval",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "requires_approval",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-03",
    auditTrailStatus: "present",
    connectedSystems: ["Customer Analytics Platform"],
    timeline: [
      { date: "2026-06-14", event: "تم تصنيف حالة الاستخدام كسير عمل (WORKFLOW)", actor: "Governance Intake" },
      { date: "2026-06-27", event: "رصد التقييم نقصًا في دليل تقييم نموذج تسرب العملاء", actor: "Eval & Grader Matrix" },
      { date: "2026-07-03", event: "تم التوجيه إلى الإصلاح لاستكمال دليل التقييم", actor: "Governance Gate" },
    ],
    lifecycleStage: "pilot",
    agentIds: ["agent-005"],
    modelId: "model-002",
    dataSourceIds: ["ds-002"],
  },
  {
    id: "uc-12",
    name: "External API Workflow Agent",
    nameAr: "وكيل سير عمل واجهات خارجية",
    department: "Operations",
    owner: "Turki Al-Anazi — Automation Engineer",
    authority: "COO Office",
    aiType: "Autonomous Workflow Agent",
    businessPurpose: "Autonomously orchestrates multi-step operational workflows across internal and external systems.",
    riskLevel: "high",
    dataSensitivity: "medium",
    toolAccess: "external_system",
    externalSystems: ["Third-party logistics API", "Partner billing API"],
    writeTools: ["Workflow orchestrator"],
    readOnlyTools: [],
    governanceStatus: "BLOCKED",
    evalScore: 35,
    evalOutcome: "FAIL",
    readinessScore: 30,
    evidenceStatus: "missing",
    authorityStatus: "missing",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: false,
      eval_evidence: false,
      audit_evidence: false,
      policy_boundary_evidence: false,
      approval_evidence: false,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "blocked",
      external_api_access: "blocked",
    },
    lastReviewed: "2026-06-10",
    auditTrailStatus: "missing",
    connectedSystems: ["Logistics API", "Billing API"],
    timeline: [
      { date: "2026-05-20", event: "تم تصنيف حالة الاستخدام كنظام متعدد الوكلاء (MULTI_AGENT_SYSTEM)", actor: "Governance Intake" },
      { date: "2026-06-10", event: "فشل التقييم — لا توجد حدود سياسة ولا سجل تدقيق", actor: "Eval & Grader Matrix" },
      { date: "2026-06-10", event: "تم الحظر لحين استكمال دليل الصلاحية وحدود السياسة", actor: "Governance Gate" },
    ],
    lifecycleStage: "pilot",
    agentIds: ["agent-006"],
    modelId: "model-006",
    vendorId: "vendor-004",
    dataSourceIds: ["ds-003", "ds-008"],
  },
  {
    id: "uc-13",
    name: "Legal Contract Drafting Agent",
    nameAr: "وكيل صياغة العقود القانونية",
    department: "Legal",
    owner: "Maha Al-Suwailem — Legal Operations Lead",
    authority: "General Counsel",
    aiType: "Drafting Agent (Assisted)",
    businessPurpose: "Drafts first-pass vendor agreement clauses from an approved clause library for legal review.",
    riskLevel: "medium",
    dataSensitivity: "medium",
    toolAccess: "write",
    externalSystems: [],
    writeTools: ["Contract draft composer"],
    readOnlyTools: ["Approved clause library"],
    governanceStatus: "GOVERNANCE_REVIEW_REQUIRED",
    evalScore: 80,
    evalOutcome: "PASS",
    readinessScore: 75,
    evidenceStatus: "partial",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: false,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "requires_approval",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-06",
    auditTrailStatus: "present",
    connectedSystems: ["Contract Repository"],
    timeline: [
      { date: "2026-06-16", event: "تم تصنيف حالة الاستخدام كوكيل (AGENT)", actor: "Governance Intake" },
      { date: "2026-06-28", event: "اجتاز مصفوفة التقييم (80/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-07-06", event: "تم ترشيحها لمراجعة الحوكمة — حدود السياسة غير مكتملة", actor: "Governance Gate" },
    ],
    lifecycleStage: "pilot",
    agentIds: [],
    modelId: "model-001",
    dataSourceIds: ["ds-010"],
  },
  {
    id: "uc-14",
    name: "IT Access Provisioning Agent",
    nameAr: "وكيل تزويد صلاحيات النظم",
    department: "Operations",
    owner: "Bandar Al-Harthi — IT Operations Lead",
    authority: "CIO Office",
    aiType: "Autonomous Workflow Agent",
    businessPurpose: "Provisions standard system access requests for new hires based on role templates.",
    riskLevel: "high",
    dataSensitivity: "high",
    toolAccess: "external_system",
    externalSystems: ["Identity and access management system"],
    writeTools: ["Access provisioning workflow"],
    readOnlyTools: ["HR role templates"],
    governanceStatus: "ESCALATE_REQUIRED",
    evalScore: 60,
    evalOutcome: "ESCALATE",
    readinessScore: 55,
    evidenceStatus: "partial",
    authorityStatus: "escalation_required",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: false,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: false,
      approval_evidence: false,
    },
    permissions: {
      read_internal_docs: "forbidden",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "requires_approval",
      external_api_access: "requires_approval",
    },
    lastReviewed: "2026-06-22",
    auditTrailStatus: "partial",
    connectedSystems: ["IAM Platform"],
    timeline: [
      { date: "2026-06-01", event: "تم تصنيف حالة الاستخدام كتشغيل محكوم (GOVERNED_RUNTIME)", actor: "Governance Intake" },
      { date: "2026-06-16", event: "رصد التقييم تصعيدًا بسبب أثر منح صلاحيات نظم حساسة", actor: "Eval & Grader Matrix" },
      { date: "2026-06-22", event: "تم التصعيد — لا توجد صلاحية معتمدة لمنح وصول تلقائي", actor: "Governance Gate" },
    ],
    lifecycleStage: "pilot",
    agentIds: [],
    modelId: "model-006",
    dataSourceIds: ["ds-006"],
  },
  {
    id: "uc-15",
    name: "Marketing Content Generator",
    nameAr: "مولّد محتوى تسويقي",
    department: "Sales",
    owner: "Dana Al-Qahtani — Marketing Manager",
    authority: "Sales Director",
    aiType: "Generation Assistant (Assisted)",
    businessPurpose: "Generates first-draft marketing copy variants for campaigns before brand review.",
    riskLevel: "low",
    dataSensitivity: "low",
    toolAccess: "none",
    externalSystems: [],
    writeTools: [],
    readOnlyTools: ["Brand guideline repository"],
    governanceStatus: "READY_FOR_AUTHORITY_REVIEW",
    evalScore: 87,
    evalOutcome: "PASS",
    readinessScore: 82,
    evidenceStatus: "complete",
    authorityStatus: "confirmed",
    evidenceDetail: {
      owner_evidence: true,
      authority_evidence: true,
      eval_evidence: true,
      audit_evidence: true,
      policy_boundary_evidence: true,
      approval_evidence: true,
    },
    permissions: {
      read_internal_docs: "allowed",
      read_customer_data: "forbidden",
      read_crm: "forbidden",
      update_crm: "forbidden",
      send_email: "forbidden",
      export_data: "forbidden",
      trigger_workflow: "forbidden",
      external_api_access: "forbidden",
    },
    lastReviewed: "2026-07-09",
    auditTrailStatus: "present",
    connectedSystems: ["Brand Asset Library"],
    timeline: [
      { date: "2026-06-19", event: "تم تصنيف حالة الاستخدام كتعزيز (AUGMENTATION)", actor: "Governance Intake" },
      { date: "2026-06-30", event: "اجتاز مصفوفة التقييم (87/100)", actor: "Eval & Grader Matrix" },
      { date: "2026-07-09", event: "تم تحديدها كجاهزة لمراجعة صاحب الصلاحية", actor: "Governance Gate" },
    ],
    lifecycleStage: "governed_runtime",
    agentIds: [],
    modelId: "model-007",
    dataSourceIds: ["ds-007"],
  },
];

export function getUseCaseById(id: string): UseCase | undefined {
  return useCases.find((u) => u.id === id);
}

// --- Layer 6: Agent Governance ----------------------------------------------

export const agents: Agent[] = [
  {
    id: "agent-001",
    name: "Email Draft Composer Agent",
    nameAr: "وكيل تحرير مسودات البريد",
    assetId: "uc-02",
    agentType: "Drafting Copilot",
    toolAccess: "write",
    status: "under_review",
    ownerTeam: "Customer Service",
    lastPermissionReview: "2026-07-02",
  },
  {
    id: "agent-002",
    name: "CRM Update Agent",
    nameAr: "وكيل تحديث نظام العملاء",
    assetId: "uc-03",
    agentType: "Write Agent",
    toolAccess: "write",
    status: "active",
    ownerTeam: "Sales",
    lastPermissionReview: "2026-06-30",
  },
  {
    id: "agent-003",
    name: "Vendor Screening Agent",
    nameAr: "وكيل فحص الموردين",
    assetId: "uc-05",
    agentType: "Decision-Support Agent",
    toolAccess: "external_system",
    status: "under_review",
    ownerTeam: "Operations",
    lastPermissionReview: "2026-06-20",
  },
  {
    id: "agent-004",
    name: "Collections Prioritization Agent",
    nameAr: "وكيل ترتيب أولويات التحصيل",
    assetId: "uc-08",
    agentType: "Decision-Support Agent",
    toolAccess: "external_system",
    status: "under_review",
    ownerTeam: "Finance",
    lastPermissionReview: "2026-06-18",
  },
  {
    id: "agent-005",
    name: "Retention Queue Agent",
    nameAr: "وكيل قائمة الاحتفاظ بالعملاء",
    assetId: "uc-11",
    agentType: "Prediction Workflow Agent",
    toolAccess: "write",
    status: "active",
    ownerTeam: "Customer Service",
    lastPermissionReview: "2026-07-03",
  },
  {
    id: "agent-006",
    name: "Workflow Orchestrator Agent",
    nameAr: "وكيل تنسيق سير العمل",
    assetId: "uc-12",
    agentType: "Autonomous Workflow Agent",
    toolAccess: "external_system",
    status: "suspended",
    ownerTeam: "Operations",
    lastPermissionReview: "2026-06-10",
  },
];

export function getAgentById(id: string): Agent | undefined {
  return agents.find((a) => a.id === id);
}

// --- Layer 3: Model Lifecycle ------------------------------------------------

export const models: ModelRecord[] = [
  {
    id: "model-001",
    name: "GPT-class Chat Model",
    provider: "OpenAI",
    version: "gpt-4.1-class",
    usedByAssetIds: ["uc-02", "uc-07", "uc-13"],
    dataResidency: "regional",
    evaluationStatus: "complete",
    lastEvaluated: "2026-06-29",
    riskTier: "medium",
    approvedForProduction: false,
  },
  {
    id: "model-002",
    name: "Claude-class Reasoning Model",
    provider: "Anthropic",
    version: "claude-sonnet-class",
    usedByAssetIds: ["uc-03", "uc-08", "uc-11"],
    dataResidency: "regional",
    evaluationStatus: "partial",
    lastEvaluated: "2026-06-27",
    riskTier: "medium",
    approvedForProduction: false,
  },
  {
    id: "model-003",
    name: "Enterprise Analytics Model",
    provider: "Microsoft",
    version: "azure-openai-class",
    usedByAssetIds: ["uc-04", "uc-09"],
    dataResidency: "in_country",
    evaluationStatus: "complete",
    lastEvaluated: "2026-07-01",
    riskTier: "low",
    approvedForProduction: false,
  },
  {
    id: "model-004",
    name: "Document Understanding Model",
    provider: "Google",
    version: "gemini-class",
    usedByAssetIds: ["uc-05", "uc-10"],
    dataResidency: "regional",
    evaluationStatus: "partial",
    lastEvaluated: "2026-06-19",
    riskTier: "medium",
    approvedForProduction: false,
  },
  {
    id: "model-005",
    name: "Internal Retrieval Model",
    provider: "Internal",
    version: "internal-embed-v2",
    usedByAssetIds: ["uc-01", "uc-06"],
    dataResidency: "in_country",
    evaluationStatus: "complete",
    lastEvaluated: "2026-06-20",
    riskTier: "low",
    approvedForProduction: false,
  },
  {
    id: "model-006",
    name: "Open-source Orchestration Model",
    provider: "Open-source",
    version: "oss-instruct-13b",
    usedByAssetIds: ["uc-12", "uc-14"],
    dataResidency: "unknown",
    evaluationStatus: "missing",
    lastEvaluated: "2026-06-10",
    riskTier: "high",
    approvedForProduction: false,
  },
  {
    id: "model-007",
    name: "Marketing Generation Model",
    provider: "OpenAI",
    version: "gpt-4.1-class",
    usedByAssetIds: ["uc-15"],
    dataResidency: "regional",
    evaluationStatus: "complete",
    lastEvaluated: "2026-06-30",
    riskTier: "low",
    approvedForProduction: false,
  },
  {
    id: "model-008",
    name: "Legacy Classification Model",
    provider: "Internal",
    version: "internal-classify-v1",
    usedByAssetIds: [],
    dataResidency: "in_country",
    evaluationStatus: "missing",
    lastEvaluated: "2026-03-12",
    riskTier: "medium",
    approvedForProduction: false,
  },
];

export function getModelById(id: string): ModelRecord | undefined {
  return models.find((m) => m.id === id);
}

// --- Vendors -------------------------------------------------------------------

export const vendors: VendorRecord[] = [
  {
    id: "vendor-001",
    name: "Northwind AI Platform Services",
    nameAr: "نورثويند لخدمات منصات الذكاء الاصطناعي",
    category: "Model hosting",
    dataAccessLevel: "medium",
    contractStatus: "active",
    riskTier: "medium",
    lastAssessed: "2026-05-15",
  },
  {
    id: "vendor-002",
    name: "Vendor Verification Services Co.",
    nameAr: "شركة خدمات التحقق من الموردين",
    category: "Third-party verification",
    dataAccessLevel: "medium",
    contractStatus: "under_review",
    riskTier: "high",
    lastAssessed: "2026-06-20",
  },
  {
    id: "vendor-003",
    name: "Regional Collections Agency",
    nameAr: "وكالة التحصيل الإقليمية",
    category: "Collections partner",
    dataAccessLevel: "high",
    contractStatus: "active",
    riskTier: "high",
    lastAssessed: "2026-06-18",
  },
  {
    id: "vendor-004",
    name: "OpenSource Model Registry",
    nameAr: "سجل النماذج مفتوحة المصدر",
    category: "Open-source model distribution",
    dataAccessLevel: "low",
    contractStatus: "expired",
    riskTier: "high",
    lastAssessed: "2026-02-28",
  },
  {
    id: "vendor-005",
    name: "Logistics API Partner",
    nameAr: "شريك واجهة الخدمات اللوجستية",
    category: "External system integration",
    dataAccessLevel: "medium",
    contractStatus: "active",
    riskTier: "medium",
    lastAssessed: "2026-05-30",
  },
];

export function getVendorById(id: string): VendorRecord | undefined {
  return vendors.find((v) => v.id === id);
}

// --- Layer 2: Data Foundation ----------------------------------------------

export const dataSources: DataSource[] = [
  {
    id: "ds-001",
    name: "Internal Policy Repository",
    nameAr: "مستودع السياسات الداخلية",
    type: "document_repository",
    sensitivity: "low",
    owner: "Operations",
    usedByAssetIds: ["uc-01"],
    classificationStatus: "complete",
    lastClassified: "2026-06-05",
  },
  {
    id: "ds-002",
    name: "Customer Support Tickets",
    nameAr: "تذاكر دعم العملاء",
    type: "structured",
    sensitivity: "medium",
    owner: "Customer Service",
    usedByAssetIds: ["uc-02", "uc-11"],
    classificationStatus: "complete",
    lastClassified: "2026-06-10",
  },
  {
    id: "ds-003",
    name: "Sales Call Transcripts",
    nameAr: "نصوص مكالمات المبيعات",
    type: "unstructured",
    sensitivity: "medium",
    owner: "Sales",
    usedByAssetIds: ["uc-03", "uc-12"],
    classificationStatus: "partial",
    lastClassified: "2026-05-28",
  },
  {
    id: "ds-004",
    name: "ERP Financial Reports",
    nameAr: "تقارير نظام تخطيط الموارد المالية",
    type: "structured",
    sensitivity: "high",
    owner: "Finance",
    usedByAssetIds: ["uc-04"],
    classificationStatus: "complete",
    lastClassified: "2026-06-25",
  },
  {
    id: "ds-005",
    name: "Procurement Records",
    nameAr: "سجلات المشتريات",
    type: "structured",
    sensitivity: "medium",
    owner: "Operations",
    usedByAssetIds: ["uc-05"],
    classificationStatus: "partial",
    lastClassified: "2026-06-01",
  },
  {
    id: "ds-006",
    name: "Applicant Tracking System Records",
    nameAr: "سجلات نظام تتبع المتقدمين",
    type: "structured",
    sensitivity: "high",
    owner: "HR",
    usedByAssetIds: ["uc-06", "uc-14"],
    classificationStatus: "missing",
    lastClassified: "2026-01-20",
  },
  {
    id: "ds-007",
    name: "Department Report Repository",
    nameAr: "مستودع تقارير الإدارات",
    type: "document_repository",
    sensitivity: "medium",
    owner: "Executive Office",
    usedByAssetIds: ["uc-07", "uc-15"],
    classificationStatus: "complete",
    lastClassified: "2026-06-15",
  },
  {
    id: "ds-008",
    name: "Accounts Receivable Data",
    nameAr: "بيانات الذمم المدينة",
    type: "structured",
    sensitivity: "high",
    owner: "Finance",
    usedByAssetIds: ["uc-08", "uc-12"],
    classificationStatus: "partial",
    lastClassified: "2026-06-05",
  },
  {
    id: "ds-009",
    name: "Sales Pipeline Data",
    nameAr: "بيانات مسار المبيعات",
    type: "structured",
    sensitivity: "low",
    owner: "Sales",
    usedByAssetIds: ["uc-09"],
    classificationStatus: "complete",
    lastClassified: "2026-06-20",
  },
  {
    id: "ds-010",
    name: "Contract Repository",
    nameAr: "مستودع العقود",
    type: "document_repository",
    sensitivity: "medium",
    owner: "Legal",
    usedByAssetIds: ["uc-10", "uc-13"],
    classificationStatus: "partial",
    lastClassified: "2026-06-12",
  },
];

export function getDataSourceById(id: string): DataSource | undefined {
  return dataSources.find((d) => d.id === id);
}

export const dataLineage: DataLineageRecord[] = [
  { id: "dl-001", dataSourceId: "ds-001", assetId: "uc-01", flowDescriptionAr: "قراءة فقط من المستودع إلى المساعد", flowDescription: "Read-only from repository into assistant" },
  { id: "dl-002", dataSourceId: "ds-002", assetId: "uc-02", flowDescriptionAr: "قراءة تذاكر الدعم لإعداد مسودة الرد", flowDescription: "Read support tickets to draft reply" },
  { id: "dl-003", dataSourceId: "ds-002", assetId: "uc-11", flowDescriptionAr: "قراءة تذاكر الدعم ضمن بيانات استخدام العميل", flowDescription: "Read support tickets as part of customer usage data" },
  { id: "dl-004", dataSourceId: "ds-003", assetId: "uc-03", flowDescriptionAr: "قراءة النصوص لتحديث سجل العميل", flowDescription: "Read transcripts to update CRM record" },
  { id: "dl-005", dataSourceId: "ds-003", assetId: "uc-12", flowDescriptionAr: "قراءة النصوص ضمن سير عمل متعدد الأنظمة", flowDescription: "Read transcripts within multi-system workflow" },
  { id: "dl-006", dataSourceId: "ds-004", assetId: "uc-04", flowDescriptionAr: "قراءة التقارير المالية لتفسير الانحرافات", flowDescription: "Read financial reports to explain variance" },
  { id: "dl-007", dataSourceId: "ds-005", assetId: "uc-05", flowDescriptionAr: "قراءة سجلات المشتريات لفحص الموردين", flowDescription: "Read procurement records to screen vendors" },
  { id: "dl-008", dataSourceId: "ds-006", assetId: "uc-06", flowDescriptionAr: "قراءة سجلات المتقدمين لترتيب السير الذاتية", flowDescription: "Read applicant records to rank CVs" },
  { id: "dl-009", dataSourceId: "ds-006", assetId: "uc-14", flowDescriptionAr: "قراءة قوالب الأدوار لتزويد الصلاحيات", flowDescription: "Read role templates to provision access" },
  { id: "dl-010", dataSourceId: "ds-007", assetId: "uc-07", flowDescriptionAr: "قراءة تقارير الإدارات لتلخيصها", flowDescription: "Read department reports to summarize" },
  { id: "dl-011", dataSourceId: "ds-007", assetId: "uc-15", flowDescriptionAr: "قراءة إرشادات العلامة التجارية لتوليد المحتوى", flowDescription: "Read brand guidelines to generate content" },
  { id: "dl-012", dataSourceId: "ds-008", assetId: "uc-08", flowDescriptionAr: "قراءة بيانات الذمم لترتيب أولويات التحصيل", flowDescription: "Read receivables data to prioritize collections" },
  { id: "dl-013", dataSourceId: "ds-009", assetId: "uc-09", flowDescriptionAr: "قراءة بيانات المسار لإعداد التنبؤ", flowDescription: "Read pipeline data to produce forecast" },
  { id: "dl-014", dataSourceId: "ds-010", assetId: "uc-10", flowDescriptionAr: "قراءة العقود لرصد البنود عالية الخطورة", flowDescription: "Read contracts to flag high-risk clauses" },
  { id: "dl-015", dataSourceId: "ds-010", assetId: "uc-13", flowDescriptionAr: "قراءة مكتبة البنود المعتمدة لصياغة العقد", flowDescription: "Read approved clause library to draft contract" },
];

// --- Layer 4: Data Security & Privacy ---------------------------------------

export const securityControls: SecurityControl[] = [
  { id: "sec-001", name: "Role-based access control on model endpoints", nameAr: "التحكم بالوصول المبني على الأدوار لنقاط النموذج", category: "access", status: "complete", appliesToAssetIds: ["uc-01", "uc-04", "uc-07", "uc-09"] },
  { id: "sec-002", name: "Encryption at rest for connected data stores", nameAr: "تشفير البيانات أثناء التخزين لمستودعات البيانات المتصلة", category: "encryption", status: "complete", appliesToAssetIds: allUseCaseIds() },
  { id: "sec-003", name: "Prompt and output logging for monitoring", nameAr: "تسجيل المدخلات والمخرجات لأغراض المراقبة", category: "monitoring", status: "partial", appliesToAssetIds: ["uc-02", "uc-03", "uc-05", "uc-08", "uc-11", "uc-12"] },
  { id: "sec-004", name: "Network segmentation for external system agents", nameAr: "فصل الشبكة لوكلاء الأنظمة الخارجية", category: "network", status: "partial", appliesToAssetIds: ["uc-05", "uc-08", "uc-12", "uc-14"] },
  { id: "sec-005", name: "Secrets management for API credentials", nameAr: "إدارة الأسرار لبيانات اعتماد الواجهات البرمجية", category: "secrets", status: "missing", appliesToAssetIds: ["uc-12", "uc-14"] },
  { id: "sec-006", name: "Rate limiting on write-capable tools", nameAr: "تحديد معدل الاستخدام لأدوات الكتابة", category: "access", status: "partial", appliesToAssetIds: ["uc-02", "uc-03", "uc-08", "uc-11", "uc-13"] },
  { id: "sec-007", name: "Anomaly monitoring for autonomous agents", nameAr: "مراقبة الحالات الشاذة للوكلاء المستقلين", category: "monitoring", status: "missing", appliesToAssetIds: ["uc-06", "uc-12"] },
  { id: "sec-008", name: "Vendor endpoint security review", nameAr: "مراجعة أمن نقاط اتصال الموردين", category: "network", status: "partial", appliesToAssetIds: ["uc-05", "uc-08", "uc-12"] },
];

export const privacyControls: PrivacyControl[] = [
  { id: "priv-001", name: "PII minimization in retrieval prompts", nameAr: "تقليل البيانات الشخصية في مدخلات الاسترجاع", category: "pii_minimization", status: "complete", appliesToAssetIds: ["uc-01", "uc-07", "uc-15"] },
  { id: "priv-002", name: "Customer data consent basis review", nameAr: "مراجعة أساس الموافقة لبيانات العملاء", category: "consent", status: "partial", appliesToAssetIds: ["uc-02", "uc-08", "uc-11"] },
  { id: "priv-003", name: "Retention limits for candidate screening data", nameAr: "حدود الاحتفاظ لبيانات فرز المتقدمين", category: "retention", status: "missing", appliesToAssetIds: ["uc-06"] },
  { id: "priv-004", name: "Anonymization of financial variance inputs", nameAr: "إخفاء الهوية لمدخلات الانحرافات المالية", category: "anonymization", status: "complete", appliesToAssetIds: ["uc-04"] },
  { id: "priv-005", name: "Third-party data sharing review", nameAr: "مراجعة مشاركة البيانات مع أطراف خارجية", category: "consent", status: "partial", appliesToAssetIds: ["uc-05", "uc-12", "uc-14"] },
  { id: "priv-006", name: "Retention limits for collections outreach data", nameAr: "حدود الاحتفاظ لبيانات تواصل التحصيل", category: "retention", status: "missing", appliesToAssetIds: ["uc-08"] },
];

function allUseCaseIds(): string[] {
  return [
    "uc-01","uc-02","uc-03","uc-04","uc-05","uc-06","uc-07","uc-08",
    "uc-09","uc-10","uc-11","uc-12","uc-13","uc-14","uc-15",
  ];
}

// --- Evaluation ledger --------------------------------------------------------

export const evaluationRecords: EvaluationRecord[] = [
  { id: "eval-001", assetId: "uc-01", evaluatedAt: "2026-06-20", score: 96, outcome: "PASS", graderNotes: "Strong grounding, no unsupported claims.", graderNotesAr: "إسناد مرجعي قوي، لا توجد ادعاءات غير مدعومة." },
  { id: "eval-002", assetId: "uc-02", evaluatedAt: "2026-06-24", score: 71, outcome: "FIX", graderNotes: "Missing citation trail for drafted replies.", graderNotesAr: "دليل الإسناد المرجعي لمسودات الردود غير مكتمل." },
  { id: "eval-003", assetId: "uc-03", evaluatedAt: "2026-06-22", score: 82, outcome: "PASS", graderNotes: "Accurate updates, policy boundary evidence pending.", graderNotesAr: "تحديثات دقيقة، دليل حدود السياسة لا يزال معلقًا." },
  { id: "eval-004", assetId: "uc-04", evaluatedAt: "2026-06-27", score: 93, outcome: "PASS", graderNotes: "Variance explanations trace correctly to ERP source.", graderNotesAr: "تفسيرات الانحراف تُسند بدقة لمصدر النظام المالي." },
  { id: "eval-005", assetId: "uc-05", evaluatedAt: "2026-06-14", score: 68, outcome: "ESCALATE", graderNotes: "Decision authority for vendor rejection is ambiguous.", graderNotesAr: "صلاحية اتخاذ قرار رفض المورد غامضة." },
  { id: "eval-006", assetId: "uc-06", evaluatedAt: "2026-06-15", score: 42, outcome: "FAIL", graderNotes: "No authority evidence, no audit trail.", graderNotesAr: "لا توجد صلاحية معتمدة ولا سجل تدقيق." },
  { id: "eval-007", assetId: "uc-07", evaluatedAt: "2026-06-29", score: 90, outcome: "PASS", graderNotes: "Summaries preserve source meaning accurately.", graderNotesAr: "الملخصات تحافظ على المعنى الأصلي بدقة." },
  { id: "eval-008", assetId: "uc-08", evaluatedAt: "2026-06-10", score: 64, outcome: "ESCALATE", graderNotes: "Customer-impact escalation required before outreach.", graderNotesAr: "يتطلب تصعيدًا بسبب التأثير على العملاء قبل التواصل." },
  { id: "eval-009", assetId: "uc-09", evaluatedAt: "2026-06-23", score: 89, outcome: "PASS", graderNotes: "Forecast variance within acceptable tolerance.", graderNotesAr: "انحراف التنبؤ ضمن الحدود المقبولة." },
  { id: "eval-010", assetId: "uc-10", evaluatedAt: "2026-06-19", score: 78, outcome: "PASS", graderNotes: "Clause flagging accurate, approval evidence pending.", graderNotesAr: "رصد البنود دقيق، دليل الموافقة لا يزال معلقًا." },
  { id: "eval-011", assetId: "uc-11", evaluatedAt: "2026-06-27", score: 73, outcome: "FIX", graderNotes: "Churn model evaluation evidence incomplete.", graderNotesAr: "دليل تقييم نموذج تسرب العملاء غير مكتمل." },
  { id: "eval-012", assetId: "uc-12", evaluatedAt: "2026-06-10", score: 35, outcome: "FAIL", graderNotes: "No policy boundary, no audit trail, multi-system risk.", graderNotesAr: "لا توجد حدود سياسة ولا سجل تدقيق، مع مخاطر تعدد الأنظمة." },
  { id: "eval-013", assetId: "uc-13", evaluatedAt: "2026-06-28", score: 80, outcome: "PASS", graderNotes: "Draft clauses match approved library patterns.", graderNotesAr: "البنود المسودة تطابق أنماط المكتبة المعتمدة." },
  { id: "eval-014", assetId: "uc-14", evaluatedAt: "2026-06-16", score: 60, outcome: "ESCALATE", graderNotes: "Sensitive-system provisioning needs authority confirmation.", graderNotesAr: "تزويد الوصول لأنظمة حساسة يحتاج تأكيد صلاحية." },
  { id: "eval-015", assetId: "uc-15", evaluatedAt: "2026-06-30", score: 87, outcome: "PASS", graderNotes: "Copy variants align with brand guidelines.", graderNotesAr: "بدائل المحتوى متوافقة مع إرشادات العلامة التجارية." },
];

// --- Layer 7: Human Oversight ------------------------------------------------

export const humanReviews: HumanReview[] = [
  { id: "review-001", assetId: "uc-01", reviewer: "Fahad Al-Otaibi", reviewDate: "2026-06-28", decision: "approved_for_next_stage", notes: "Cleared for authority review.", notesAr: "تم اعتمادها للانتقال لمراجعة صاحب الصلاحية." },
  { id: "review-002", assetId: "uc-02", reviewer: "Lama Al-Harbi", reviewDate: "2026-07-02", decision: "returned_for_repair", notes: "Requires citation evidence before resubmission.", notesAr: "تحتاج دليل إسناد مرجعي قبل إعادة العرض." },
  { id: "review-003", assetId: "uc-03", reviewer: "Yousef Al-Qahtani", reviewDate: "2026-06-30", decision: "returned_for_repair", notes: "Policy boundary must be documented.", notesAr: "يجب توثيق حدود السياسة." },
  { id: "review-004", assetId: "uc-05", reviewer: "Khalid Al-Zahrani", reviewDate: "2026-06-20", decision: "escalated", notes: "No confirmed authority for vendor rejection decisions.", notesAr: "لا توجد صلاحية مؤكدة لقرارات رفض الموردين." },
  { id: "review-005", assetId: "uc-06", reviewer: "Sara Al-Ghamdi", reviewDate: "2026-06-15", decision: "returned_for_repair", notes: "Blocked pending owner and authority evidence.", notesAr: "محظورة لحين استكمال دليل المالك والصلاحية." },
  { id: "review-006", assetId: "uc-08", reviewer: "Mansour Al-Shehri", reviewDate: "2026-06-18", decision: "escalated", notes: "Customer-impact escalation required.", notesAr: "يتطلب تصعيدًا بسبب الأثر على العملاء." },
  { id: "review-007", assetId: "uc-10", reviewer: "Hana Al-Amri", reviewDate: "2026-06-25", decision: "approved_for_next_stage", notes: "Routed to governance review committee.", notesAr: "تم توجيهها إلى لجنة مراجعة الحوكمة." },
  { id: "review-008", assetId: "uc-11", reviewer: "Faisal Al-Mutairi", reviewDate: "2026-07-03", decision: "returned_for_repair", notes: "Eval evidence for churn model required.", notesAr: "يلزم استكمال دليل تقييم نموذج التسرب." },
  { id: "review-009", assetId: "uc-12", reviewer: "Turki Al-Anazi", reviewDate: "2026-06-10", decision: "returned_for_repair", notes: "Blocked — no policy boundary or audit trail.", notesAr: "محظورة — لا توجد حدود سياسة ولا سجل تدقيق." },
  { id: "review-010", assetId: "uc-14", reviewer: "Bandar Al-Harthi", reviewDate: "2026-06-22", decision: "escalated", notes: "Sensitive access provisioning needs institutional authority.", notesAr: "تزويد الوصول الحساس يحتاج صلاحية مؤسسية." },
];

// --- Incidents (Human Oversight + Compliance) --------------------------------

export const incidents: IncidentRecord[] = [
  { id: "inc-001", assetId: "uc-12", title: "Unauthorized external API call attempt", titleAr: "محاولة استدعاء غير مصرح بها لواجهة خارجية", severity: "high", status: "resolved", reportedDate: "2026-06-11", resolvedDate: "2026-06-13", summaryAr: "رصد سجل التدقيق محاولة استدعاء لواجهة الفوترة خارج حدود السياسة، وتم تعليق الوكيل فورًا." },
  { id: "inc-002", assetId: "uc-06", title: "Screening output used without authority sign-off", titleAr: "استخدام مخرجات الفرز دون اعتماد صلاحية", severity: "high", status: "investigating", reportedDate: "2026-06-16", summaryAr: "استُخدمت نتائج الفرز في قرار توظيف قبل استكمال دليل الصلاحية المعتمدة." },
  { id: "inc-003", assetId: "uc-05", title: "Vendor verification data shared beyond scope", titleAr: "مشاركة بيانات التحقق من المورد خارج النطاق", severity: "medium", status: "resolved", reportedDate: "2026-06-15", resolvedDate: "2026-06-19", summaryAr: "تمت مشاركة بيانات تحقق مع طرف ثالث غير مدرج في نطاق العقد، وتم تصحيح ضوابط المشاركة." },
  { id: "inc-004", assetId: "uc-08", title: "Collections outreach triggered before escalation review", titleAr: "تشغيل تواصل التحصيل قبل مراجعة التصعيد", severity: "medium", status: "investigating", reportedDate: "2026-06-19", summaryAr: "أطلق الوكيل قائمة تواصل قبل استكمال مراجعة التصعيد المطلوبة." },
  { id: "inc-005", assetId: "uc-14", title: "Access template misapplied to elevated role", titleAr: "تطبيق قالب صلاحيات خاطئ على دور مرتفع الحساسية", severity: "high", status: "open", reportedDate: "2026-06-23", summaryAr: "طُبق قالب وصول قياسي على دور يتطلب مستوى صلاحية أعلى قبل تصحيح الخطأ." },
];

// --- Layer 8: Compliance & Audit ---------------------------------------------

export const auditEvents: AuditEvent[] = [
  { id: "audit-001", timestamp: "2026-06-10T09:12:00Z", actor: "Governance Intake", action: "Classified use case as AUTOMATION", actionAr: "تصنيف حالة الاستخدام كأتمتة", assetId: "uc-01", layer: "ai_inventory" },
  { id: "audit-002", timestamp: "2026-06-20T10:30:00Z", actor: "Eval & Grader Matrix", action: "Evaluation passed at 96/100", actionAr: "اجتياز التقييم بدرجة 96/100", assetId: "uc-01", layer: "ai_inventory" },
  { id: "audit-003", timestamp: "2026-06-05T08:00:00Z", actor: "Data Foundation", action: "Classified Internal Policy Repository as low sensitivity", actionAr: "تصنيف مستودع السياسات الداخلية كحساسية منخفضة", assetId: "uc-01", layer: "data_foundation" },
  { id: "audit-004", timestamp: "2026-06-12T11:45:00Z", actor: "Governance Intake", action: "Classified use case as AUGMENTATION", actionAr: "تصنيف حالة الاستخدام كتعزيز", assetId: "uc-02", layer: "ai_inventory" },
  { id: "audit-005", timestamp: "2026-06-24T14:05:00Z", actor: "Eval & Grader Matrix", action: "Flagged missing citation evidence", actionAr: "رصد نقصًا في دليل الإسناد المرجعي", assetId: "uc-02", layer: "ai_inventory" },
  { id: "audit-006", timestamp: "2026-07-02T09:20:00Z", actor: "Agent Permission Schema", action: "Reviewed write-tool permission for email composer", actionAr: "مراجعة صلاحية أداة الكتابة لمحرر البريد", assetId: "uc-02", layer: "agent_governance" },
  { id: "audit-007", timestamp: "2026-06-05T07:30:00Z", actor: "Governance Intake", action: "Classified use case as AGENT", actionAr: "تصنيف حالة الاستخدام كوكيل", assetId: "uc-03", layer: "ai_inventory" },
  { id: "audit-008", timestamp: "2026-06-30T13:10:00Z", actor: "Governance Gate", action: "Routed to governance review — incomplete policy boundary", actionAr: "توجيه لمراجعة الحوكمة — حدود السياسة غير مكتملة", assetId: "uc-03", layer: "access_control" },
  { id: "audit-009", timestamp: "2026-06-27T10:00:00Z", actor: "Eval & Grader Matrix", action: "Evaluation passed at 93/100", actionAr: "اجتياز التقييم بدرجة 93/100", assetId: "uc-04", layer: "ai_inventory" },
  { id: "audit-010", timestamp: "2026-06-25T09:00:00Z", actor: "Data Security & Privacy", action: "Confirmed anonymization control for financial inputs", actionAr: "تأكيد ضابط إخفاء الهوية لمدخلات الانحرافات المالية", assetId: "uc-04", layer: "data_security_privacy" },
  { id: "audit-011", timestamp: "2026-06-14T12:15:00Z", actor: "Eval & Grader Matrix", action: "Flagged ambiguous decision authority", actionAr: "رصد غموضًا في صلاحية اتخاذ القرار", assetId: "uc-05", layer: "ai_inventory" },
  { id: "audit-012", timestamp: "2026-06-20T15:40:00Z", actor: "Governance Gate", action: "Escalated — no confirmed authority for vendor rejection", actionAr: "تصعيد — لا توجد صلاحية معتمدة لرفض المورد", assetId: "uc-05", layer: "human_oversight" },
  { id: "audit-013", timestamp: "2026-06-15T08:50:00Z", actor: "Eval & Grader Matrix", action: "Evaluation failed — missing authority and audit evidence", actionAr: "فشل التقييم — دليل الصلاحية والتدقيق مفقود", assetId: "uc-06", layer: "ai_inventory" },
  { id: "audit-014", timestamp: "2026-06-15T09:05:00Z", actor: "Governance Gate", action: "Blocked pending owner and authority evidence", actionAr: "حظر لحين استكمال دليل المالك والصلاحية", assetId: "uc-06", layer: "human_oversight" },
  { id: "audit-015", timestamp: "2026-06-29T11:00:00Z", actor: "Eval & Grader Matrix", action: "Evaluation passed at 90/100", actionAr: "اجتياز التقييم بدرجة 90/100", assetId: "uc-07", layer: "ai_inventory" },
  { id: "audit-016", timestamp: "2026-06-10T10:20:00Z", actor: "Eval & Grader Matrix", action: "Escalation triggered by customer-impact risk", actionAr: "تصعيد بسبب مخاطر التأثير على العملاء", assetId: "uc-08", layer: "human_oversight" },
  { id: "audit-017", timestamp: "2026-06-11T16:00:00Z", actor: "Data Security & Privacy", action: "Logged unauthorized external API call attempt", actionAr: "تسجيل محاولة استدعاء غير مصرح بها لواجهة خارجية", assetId: "uc-12", layer: "data_security_privacy" },
  { id: "audit-018", timestamp: "2026-06-23T09:40:00Z", actor: "Eval & Grader Matrix", action: "Evaluation passed at 89/100", actionAr: "اجتياز التقييم بدرجة 89/100", assetId: "uc-09", layer: "ai_inventory" },
  { id: "audit-019", timestamp: "2026-06-19T10:10:00Z", actor: "Eval & Grader Matrix", action: "Evaluation passed at 78/100", actionAr: "اجتياز التقييم بدرجة 78/100", assetId: "uc-10", layer: "ai_inventory" },
  { id: "audit-020", timestamp: "2026-06-27T13:30:00Z", actor: "Eval & Grader Matrix", action: "Flagged incomplete churn model evaluation evidence", actionAr: "رصد نقصًا في دليل تقييم نموذج تسرب العملاء", assetId: "uc-11", layer: "ai_inventory" },
  { id: "audit-021", timestamp: "2026-06-10T08:10:00Z", actor: "Eval & Grader Matrix", action: "Evaluation failed — no policy boundary or audit trail", actionAr: "فشل التقييم — لا توجد حدود سياسة ولا سجل تدقيق", assetId: "uc-12", layer: "ai_inventory" },
  { id: "audit-022", timestamp: "2026-06-10T08:15:00Z", actor: "Governance Gate", action: "Blocked pending authority and policy boundary evidence", actionAr: "حظر لحين استكمال دليل الصلاحية وحدود السياسة", assetId: "uc-12", layer: "agent_governance" },
  { id: "audit-023", timestamp: "2026-06-28T09:00:00Z", actor: "Eval & Grader Matrix", action: "Evaluation passed at 80/100", actionAr: "اجتياز التقييم بدرجة 80/100", assetId: "uc-13", layer: "ai_inventory" },
  { id: "audit-024", timestamp: "2026-06-16T11:20:00Z", actor: "Eval & Grader Matrix", action: "Escalation triggered by sensitive-system provisioning", actionAr: "تصعيد بسبب تزويد وصول لأنظمة حساسة", assetId: "uc-14", layer: "access_control" },
  { id: "audit-025", timestamp: "2026-06-23T08:30:00Z", actor: "Governance Gate", action: "Logged access template misapplication incident", actionAr: "تسجيل حادثة تطبيق قالب صلاحيات خاطئ", assetId: "uc-14", layer: "human_oversight" },
  { id: "audit-026", timestamp: "2026-06-30T10:45:00Z", actor: "Eval & Grader Matrix", action: "Evaluation passed at 87/100", actionAr: "اجتياز التقييم بدرجة 87/100", assetId: "uc-15", layer: "ai_inventory" },
  { id: "audit-027", timestamp: "2026-06-01T09:00:00Z", actor: "Compliance & Audit", action: "Mapped access control evidence to internal access policy", actionAr: "ربط دليل التحكم بالوصول بسياسة الوصول الداخلية", layer: "compliance_audit" },
  { id: "audit-028", timestamp: "2026-05-20T07:45:00Z", actor: "Model Lifecycle", action: "Flagged open-source model as unreviewed for data residency", actionAr: "رصد نموذج مفتوح المصدر كغير مراجَع من حيث إقامة البيانات", assetId: "uc-12", layer: "model_lifecycle" },
];

export const complianceMappings: ComplianceMapping[] = [
  { id: "cm-001", frameworkName: "Internal AI Governance Policy", requirement: "Every AI use case must have a confirmed business owner.", requirementAr: "يجب أن يكون لكل حالة استخدام مالك عمل مؤكد.", mappedControlIds: ["sec-001"], status: "complete" },
  { id: "cm-002", frameworkName: "Internal AI Governance Policy", requirement: "Every AI use case must have a confirmed institutional authority.", requirementAr: "يجب أن يكون لكل حالة استخدام صلاحية مؤسسية مؤكدة.", mappedControlIds: [], status: "partial" },
  { id: "cm-003", frameworkName: "Data Protection Baseline", requirement: "High-sensitivity data sources must have a documented classification.", requirementAr: "يجب توثيق تصنيف مصادر البيانات عالية الحساسية.", mappedControlIds: ["priv-001"], status: "partial" },
  { id: "cm-004", frameworkName: "Data Protection Baseline", requirement: "Third-party data sharing must have a documented consent basis.", requirementAr: "يجب توثيق أساس الموافقة عند مشاركة البيانات مع أطراف خارجية.", mappedControlIds: ["priv-002", "priv-005"], status: "partial" },
  { id: "cm-005", frameworkName: "Security Control Baseline", requirement: "Write-capable agents must have rate limiting controls.", requirementAr: "يجب أن تخضع الوكلاء ذات صلاحية الكتابة لتحديد معدل الاستخدام.", mappedControlIds: ["sec-006"], status: "partial" },
  { id: "cm-006", frameworkName: "Security Control Baseline", requirement: "External-system agents must have network segmentation controls.", requirementAr: "يجب أن تخضع وكلاء الأنظمة الخارجية لفصل الشبكة.", mappedControlIds: ["sec-004"], status: "partial" },
  { id: "cm-007", frameworkName: "Model Risk Baseline", requirement: "Every production-track model must have a documented risk tier.", requirementAr: "يجب توثيق درجة المخاطرة لكل نموذج على مسار الإنتاج.", mappedControlIds: [], status: "complete" },
  { id: "cm-008", frameworkName: "Model Risk Baseline", requirement: "Open-source models must have a data residency review.", requirementAr: "يجب مراجعة إقامة البيانات للنماذج مفتوحة المصدر.", mappedControlIds: [], status: "missing" },
  { id: "cm-009", frameworkName: "Human Oversight Baseline", requirement: "High-risk use cases must have a documented human review decision.", requirementAr: "يجب توثيق قرار مراجعة بشرية لحالات الاستخدام عالية الخطورة.", mappedControlIds: [], status: "partial" },
  { id: "cm-010", frameworkName: "Human Oversight Baseline", requirement: "Incidents must be logged with severity and resolution status.", requirementAr: "يجب تسجيل الحوادث مع درجة الخطورة وحالة الحل.", mappedControlIds: [], status: "complete" },
  { id: "cm-011", frameworkName: "Audit Trail Baseline", requirement: "Governance gate transitions must be recorded as audit events.", requirementAr: "يجب تسجيل انتقالات بوابة الحوكمة كأحداث تدقيق.", mappedControlIds: [], status: "complete" },
  { id: "cm-012", frameworkName: "Audit Trail Baseline", requirement: "Vendor risk assessments must be refreshed within a defined cycle.", requirementAr: "يجب تحديث تقييمات مخاطر الموردين ضمن دورة محددة.", mappedControlIds: [], status: "partial" },
];
